export const styles = {
  outerContainer: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    marginLeft: '10vw',
    marginRight: '10vw'
  },
  headerContainer: {
    display: 'flex',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: '45.5vw',
    marginRight: '45.5vw',
    height: '70px',
    color: 'black',
    borderBottom: '3px solid black',
  },
  header: {
    fontFamily: 'Roboto',
    fontSize: '40px',
    fontWeight: 'bold',
  },
  innerContainer: {
    marginTop: '5vw',
    display: 'flex',
    flex: 4,
    flexDirection: 'row',
  },
  carouselContainer: {
    flex: 1
  },
  imageContainer: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    maxWidth: '25em'
  },
  bioContainer: {
    display: 'flex',
    flex: 3,
    flexDirection: 'column',
  },
  textContainer: {
    display: 'flex',
    flexDirection: 'column',
    lineHeight: '2',
    marginTop: '-0.1vw'
  },
  textSmall: {
    fontFamily: 'Roboto',
    flex: 1,
    fontSize: '14.5px',
    marginLeft: '3.5vw'
  },
  textMedium: {
    fontFamily: 'Roboto',
    flex: 1,
    fontSize: '18px',
    marginLeft: '5vw',
    fontWeight: '100',
    fontStyle: 'normal',
  },
  textLarge: {
    fontFamily: 'Roboto',
    flex: 1,
    fontSize: '22.5px',
    marginLeft: '8vw',
    fontWeight: '100',
    fontStyle: 'normal',
  },
  bioImageSmall: {
    width: '300px',
    height: '300px',
    borderRadius: '20px',
    marginLeft: '-3.5vw'
  },
  bioImageMedium: {
    width: '350px',
    height: '350px',
    borderRadius: '20px',
    marginLeft: '2vw',
  },
  bioImageLarge: {
    width: '400px',
    height: '400px',
    borderRadius: '20px',
    marginLeft: '5vw',
  },
  buttonSmall: {
    fontSize: '22px',
    fontFamily: 'Roboto',
    flex: 1,
    letterSpacing: '3px',
    backgroundColor: '#00ABCD',
    color: 'white',
    borderRadius: '10px',
    height: '40px',
    outline: 'none',
    border: '0px',
    paddingLeft: '2.5vw',
    paddingRight: '2.5vw',
  },
  buttonMedium: {
    fontSize: '22px',
    fontFamily: 'Roboto',
    flex: 1,
    letterSpacing: '3px',
    backgroundColor: '#00ABCD',
    color: 'white',
    borderRadius: '10px',
    height: '45px',
    outline: 'none',
    border: '0px',
    paddingLeft: '2.5vw',
    paddingRight: '2.5vw',
  },
  buttonLarge: {
    fontSize: '30px',
    fontFamily: 'Roboto',
    flex: 1,
    letterSpacing: '3px',
    backgroundColor: '#00ABCD',
    color: 'white',
    borderRadius: '10px',
    height: '60px',
    outline: 'none',
    border: '0px',
    paddingLeft: '2.5vw',
    paddingRight: '2.5vw',
  },
  linkContainer: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '1.75em',
  },
};
