const backgroundColor = '#4F4F4F';

export const styles = {
  outerContainer: {
    display: 'flex',
    backgroundColor: `${backgroundColor}`,
    zIndex: '0',
  },
  rowSpace: {
    paddingTop: '2em',
    flex: 1,
    backgroundColor: `${backgroundColor}`,
  },
  formContainer: {
    paddingTop: '2em',
    marginTop: '2em',
    display: 'flex',
    flexDirection: 'column',
    flex: 6,
    backgroundColor: `${backgroundColor}`,
    color: 'white',
  },
  interestedText: {
    flex: 1,
    fontFamily: 'Roboto',
    fontSize: '50px',
    marginBottom: '0.75em',
    backgroundColor: `${backgroundColor}`,
  },
  labelStyle: {
    flex: 1,
    fontFamily: 'Roboto-Light',
    fontSize: '25px',
    marginBottom: '0.5em',
  },
  nameBox: {
    flex: 1,
    width: '30vw',
    borderRadius: '5px',
    height: '2.5em',
    border: '1px solid white',
    marginBottom: '1.5em',
    backgroundColor: `${backgroundColor}`,
    outline: 'none',
    paddingLeft: '10px',
    paddingTop: '5px',
    resize: 'none',
  },
  emailBox: {
    flex: 1,
    width: '30vw',
    borderRadius: '5px',
    height: '2.5em',
    border: '1px solid white',
    marginBottom: '1.5em',
    backgroundColor: `${backgroundColor}`,
    outline: 'none',
    paddingLeft: '10px',
    paddingTop: '5px',
    resize: 'none',
  },
  messageStyle: {
    flex: 1,
    width: '50vw',
    borderRadius: '5px',
    height: '7em',
    border: '1px solid white',
    marginBottom: '1.5em',
    backgroundColor: `${backgroundColor}`,
    outline: 'none',
    paddingLeft: '10px',
    paddingTop: '5px',
    resize: 'none',
  },
  submitButton: {
    flex: 1,
    width: '20vw',
    fontSize: '25px',
    fontFamily: 'Roboto',
    letterSpacing: '5px',
    backgroundColor: '#00ABCD',
    color: 'white',
    borderRadius: '10px',
    height: '60px',
    maxWidth: '30%',
    outline: 'none',
    border: '0px',
    marginBottom: '3em',
  },
  logoContainer: {
    display: 'flex',
    flexDirection: 'column',
    flex: 3,
    paddingTop: '2em',
    marginTop: '2em',
    alignItems: 'center',
  }
};
